CREATE TABLE LineItems_2NF
(
DonutID INT NOT NULL,
OrderID INT NOT NULL,
QUANTITY INT NOT NULL,
CONSTRAINT FK_LineItems_2NF_Order FOREIGN KEY (OrderID) REFERENCES Orders_2NF(OrderID),
CONSTRAINT FK_LineItems_2NF_Donut FOREIGN KEY (DonutID) REFERENCES Donuts_2NF(DonutID),
CONSTRAINT PK_LineItems_2NF PRIMARY KEY (OrderID,DonutID)
);